/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaolj_mylibrary_A770Gpio */

#ifndef _Included_com_xiaolj_mylibrary_A770Gpio
#define _Included_com_xiaolj_mylibrary_A770Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaolj_mylibrary_A770Gpio
 * Method:    getGpioTable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xiaolj_mylibrary_A770Gpio_getGpioTable
  (JNIEnv *env, jobject job, jint a)
  {
    return a;
  }

/*
 * Class:     com_xiaolj_mylibrary_A770Gpio
 * Method:    setGpioLevel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xiaolj_mylibrary_A770Gpio_setGpioLevel
  (JNIEnv *env, jobject job, jint a, jint b)
  {
    return a + b;
  }

/*
 * Class:     com_xiaolj_mylibrary_A770Gpio
 * Method:    getGpioLevel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xiaolj_mylibrary_A770Gpio_getGpioLevel
  (JNIEnv *env, jobject jobj, jint a, jint b)
  {
    return a - b;
  }

#ifdef __cplusplus
}
#endif
#endif
