/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaolj_mylibrary_A770Gpio */

#ifndef _Included_com_xiaolj_mylibrary_A770Gpio
#define _Included_com_xiaolj_mylibrary_A770Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaolj_mylibrary_A770Gpio
 * Method:    getGpioTable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xiaolj_mylibrary_A770Gpio_getGpioTable
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xiaolj_mylibrary_A770Gpio
 * Method:    setGpioLevel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xiaolj_mylibrary_A770Gpio_setGpioLevel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_xiaolj_mylibrary_A770Gpio
 * Method:    getGpioLevel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xiaolj_mylibrary_A770Gpio_getGpioLevel
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
